__title__ = 'curequests'
__description__ = 'Curio + Requests: Async HTTP for Humans.'
__url__ = 'https://github.com/guyskk/curequests'
__version__ = '0.3.0'
__author__ = 'guyskk'
__author_email__ = 'guyskk@qq.com'
__license__ = 'MIT'
